# Configuration file for packaging
# See https://packaging.python.org/en/latest/guides/writing-pyproject-toml for details

[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "osl-dynamics"
version = "3.2.dev4"
description = "Toolbox for studying dynamic functional brain networks in MEG, EEG and fMRI data"
readme = {file = "README.md", content-type = "text/markdown"}
license = "Apache-2.0"
requires-python = ">=3.8"
keywords = [
    "neuroimaging",
    "neuroscience",
    "MEG",
    "EEG",
    "fMRI",
    "electrophysiology",
    "brain dynamics",
    "brain networks",
    "dynamic functional connectivity",
    "hidden markov model",
    "resting state",
    "burst detection",
    "spectral analysis",
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Science/Research",
    "Operating System :: MacOS",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Bio-Informatics",
    "Topic :: Scientific/Engineering :: Medical Science Apps.",
]

[project.urls]
"Homepage" = "https://github.com/OHBA-analysis/osl-dynamics"
"Documentation" = "https://osl-dynamics.readthedocs.io/en/latest/"

[project.scripts]
osl-dynamics = "osl_dynamics.config_api.pipeline:osl_dynamics_cli"

[tool.setuptools.packages.find]
where = ["."]

[tool.setuptools]
include-package-data = true

[tool.setuptools.package-data]
"*" = ["*"]

[tool.codespell]
# Ref: https://github.com/codespell-project/codespell#using-a-config-file
skip = '.git*,*.pdf,*.gii,*.scene'
check-hidden = true
# ignore-regex = ''
ignore-words-list = 'fo,fro,commun'
