HiddenSemiMarkovSimulation:
  e_std: 0.2
  full_trans_prob: null
  gamma_scale: 10
  gamma_shape: 5
  n_channels: 7
  n_samples: 50000
  n_states: 4
  off_diagonal_trans_prob: null
  random_covariance_weights: false
  sim_varying_means: false
  stay_prob: 0.95

dataset:
  mini_batch_length: 500
  batch_size: 32

model:
  dropout_rate: 0.4
  n_units_inference: 50
  n_units_model: 50
  n_states: 4
  n_channels: null
  learn_means: false
  learn_covariances: true
  alpha_xform: "softmax"
  log_likelihood_diagonal_constant: 1.0e-8

trainer:
  lr: 0.01
  annealing_scale: 0.0001
  annealing_sharpness: 20
  burn_in: 20
