header:
  # We assign a time stamp for each batch training
  time: 2024-02-05T17:00:00.000Z
  # Add custom notes, which will also be saved
  note: "Default configuration for simulation data"
# where to read the data
load_data:
  inputs: './data/node_timeseries/3T_HCP1200_MSMAll_d25_ts2/'
  prepare:
    select:
      timepoints:
        - 0
        - 1200
    standardize: {}
# Where to save model training results
save_dir: './results_yaml_test/'
# where to load the spatial map and spatial surface map
spatial_map: './data/spatial_maps/groupICA_3T_HCP1200_MSMAll_d25.ica'
non_batch_variable:
  n_channels: 25
  sequence_length: 400
  batch_size: 64
  learn_means: false
  learn_covariances: true
  learn_trans_prob: true
  learning_rate: 0.01
  n_epochs: 30
  split_strategy: random
  init_kwargs:
    n_init: 10
    n_epochs: 2
# The following variables have lists for batch training
batch_variable:
  model:
    - 'hmm'
  n_states: [2,3,4,5,6,7,8,9,10,11,12,13,14,15,16]
  # Mode can be: train, repeat, split, cross_validation
  mode:
    - train
    - repeat_1
    - repeat_2
    - repeat_3
    - repeat_4
    - repeat_5
    - split_1
    - split_2
    - split_3
    - split_4
    - split_5
    - cv_1
    - cv_2
    - cv_3
    - cv_4
    - cv_5


