# This is a basic workflow to help you get started with Actions

name: Check Black compatibility

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install black
      run: |
        python -m pip install --upgrade pip
        python -m pip install black

    - name: Run black
      run: black --check .
